### ISSUE TITLE
TTransportException: TSocket read 0 bytes

### ISSUE THREAD

**Issue by petromir** [Fitbit/thriftcli#32]
When I tried to run this in a virtual environment:
```
(thriftcli) user:~$ thriftcli localhost:8914 Service.getEntity ~/Thrift/definition.thrift -I ~/Thrift/common -b '{"request":{"filter":{"id":"1"}}'
```

I got this:
```
No handlers could be found for logger "thrift.transport.sslcompat"
/Users/user/thriftcli/lib/python2.7/site-packages/requests_kerberos/kerberos_.py:10: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
Traceback (most recent call last):
  File "/Users/user/thriftcli/bin/thriftcli", line 8, in <module>
    sys.exit(main())
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thriftcli/thrift_cli.py", line 307, in main
    _run_cli(*_parse_namespace(args))
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thriftcli/thrift_cli.py", line 277, in _run_cli
    proxy=proxy
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thriftcli/thrift_cli.py", line 62, in __init__
    thrift_dir_paths=thrift_dir_paths, client_id=client_id, proxy=proxy)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thriftcli/thrift_executor.py", line 61, in __init__
    self._open_connection(server_address)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thriftcli/thrift_executor.py", line 160, in _open_connection
    self._protocol = TFinagleProtocol(self._transport, client_id=self._client_id)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/twitter/common/rpc/finagle/protocol.py", line 70, in __init__
    upgrade_protocol_to_finagle(self)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/twitter/common/rpc/finagle/protocol.py", line 59, in upgrade_protocol_to_finagle
    return recv(protocol)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/twitter/common/rpc/finagle/protocol.py", line 45, in recv
    (fname, mtype, rseqid) = protocol.readMessageBegin()
  File "/Users/user/thriftcli/lib/python2.7/site-packages/twitter/common/rpc/finagle/protocol.py", line 98, in readMessageBegin
    return TBinaryProtocol.TBinaryProtocolAccelerated.readMessageBegin(self, *args, **kwargs)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 134, in readMessageBegin
    sz = self.readI32()
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thrift/protocol/TBinaryProtocol.py", line 217, in readI32
    buff = self.trans.readAll(4)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 283, in read
    self.readFrame()
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 287, in readFrame
    buff = self.__trans.readAll(4)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thrift/transport/TTransport.py", line 62, in readAll
    chunk = self.read(sz - have)
  File "/Users/user/thriftcli/lib/python2.7/site-packages/thrift/transport/TSocket.py", line 143, in read
    message='TSocket read 0 bytes')
thrift.transport.TTransport.TTransportException: TSocket read 0 bytes
```

**Comment by vtatai** [comment]
@petromir are you running from source, or from pypi?

**Comment by petromir** [comment]
@vtatai I've used `pip install thriftcli`

**Comment by greeflas** [comment]
@vtatai does this tool support [multiplexed protocol](https://github.com/apache/thrift/blob/master/lib/py/src/protocol/TMultiplexedProtocol.py)? I think it's may be the reason.
